### ISSUE TITLE
cppcheck hook

### ISSUE THREAD

**Issue by C47D** [pocc/pre-commit-hooks#24]
Hi,

Thanks for putting this repo together, I just found out about the pre-commit framework after a week of trying to make my own hooks work on my Windows 10 machine and it's much easier to use. This is more a question than a issue.

I'm currently working on a C project and I'm setting on my workflow to launch both `clang-format` and `cppcheck` hooks on my files (and ignoring some third party files)

 My first question is, if I want to run `cppcheck` on multiple files, does the following `.pre-commit-config.yaml` should be able to launch cppcheck on all the `.c` and `.h` files under my `lm/src` directory?

```
# Exclude vendor autogenerated files
exclude: 'Core'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    # Don't let commit in the master branch
    -   id: no-commit-to-branch
        args: ['--branch', 'master']

-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.1.1
    hooks:
    # -   id: clang-format
    #     args: [--style=file]
    -   id: cppcheck
        args: ['--quiet', '--enable=all' '--inline-suppr']
        # Run on files with c or h extension on lm directory
        files: 'lm/src/\.(c)$'
```

The output I'm getting:
```
Trim Trailing Whitespace.................................................Passed
Don't commit to branch...................................................Passed
cppcheck.............................................(no files to check)Skipped
```

I've cppcheck v2.3 installed on my Windows 10 machine tho.

Regards
