### ISSUE TITLE
Is it possible to generate compile_commands.json as part of the hook?

### ISSUE THREAD

**Issue by ivaigult** [pocc/pre-commit-hooks#32]
Usually `compile_commands.json` is created by the build system at the build or generation time. It is never stored in a repo.

Is it possible to add extra option so the database is generated automatically somehow? I can think of this syntax:
```
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: python
    hooks:
      - id: clang-tidy
        args: [-p __compdb/compile_commands.json]
        generate_compile_commands: ["mkdir __compdb", "cd __compdb", "cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"]
```

Is something like this available? Would it make sense?
