### ISSUE TITLE
clang-tidy fails due to warnings in non-user code

### ISSUE THREAD

**Issue by MarkKoz** [pocc/pre-commit-hooks#36]
If I include a standard header e.g. `stdio.h`, clang-tidy will analyse it and fail because the header's content doesn't comply with the checks:

> 2816 warnings generated.
Suppressed 2816 warnings (2816 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.

In the context of pre-commit, this is a problem because it causes the process to exit with code 1. Therefore, the check fails even though these warnings are being "suppressed". clang-tidy clearly knows these warnings are not from user code, yet I cannot find a way to make it stop exiting with code 1 (`--quiet` doesn't help). I'm a novice with clang-tidy, so I may have misconfigured something.

With this in mind, how is it even practical to use clang-tidy at all with pre-commit? How do you use it?

**Comment by MarkKoz** [comment]
Actually, it only seems to exit with code 1 through pre-commit. If I invoke `clang-tidy` directly, it shows the warnings were suppressed but exits with code 0.

```
clang-tidy...............................................................Failed
- hook id: clang-tidy
- exit code: 1

2816 warnings generated.
Suppressed 2816 warnings (2816 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
```

```yaml
repos:
    - repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.3.3
      hooks:
          - id: clang-format
            args: [-i, --style=file]
          - id: clang-tidy
            args: [--fix, -p=cmake-build-debug]
```
