### ISSUE TITLE
clang-tidy stops working when using --version

### ISSUE THREAD

**Issue by mintar** [pocc/pre-commit-hooks#44]
With the default test repo (`pre-commit-hooks/tests/test_repo`) and the following config...

```yaml
fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--version=10.0.0, --style=Google]
```

... the following happens (incorrectly, it should detect the incorrect formatting):

```
$ pre-commit run -a
clang-format.............................................................Passed
```

But when I remove `--version=10.0.0`, it's working:

```
$ pre-commit run -a
clang-format.............................................................Failed
- hook id: clang-format
- exit code: 1

err.cpp
====================
--- original

+++ formatted

@@ -1,2 +1,5 @@

 #include <string>
-int main(){int i;return;}
+int main() {
+  int i;
+  return;
+}
err.c
====================
--- original

+++ formatted

@@ -1,2 +1,5 @@

 #include <stdio.h>
-int main(){int i;return;}
+int main() {
+  int i;
+  return;
+}
```
