### ISSUE TITLE
clang-tidy ignores provided `-p` option

### ISSUE THREAD

**Issue by sparfenyuk** [pocc/pre-commit-hooks#5]
I am trying to set the directory where compile_commands.json file exists by using -p argument. Clang-tidy hook doesn't use it much. It causes errors while the tool looks for external libraries that are used in the project.
```
fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
        types: [c++]
      - id: clang-tidy
        args: [-p=/home/user/projects/myproject/build]
```
