### ISSUE TITLE
can I add few more arguments for clang-format and clang-tidy?

### ISSUE THREAD

**Issue by sangshuduo** [pocc/pre-commit-hooks#50]
I tried to look for answers from early issues but was still confused if it was possible or impossible or on the to-do list.
I think both clang-format and clang-tidy usually need multiple arguments for customization.
Sorry if I missed any critical document already described it.

**Comment by gsmithufl** [comment]
For clang-format, with a `.clang-format file in the base of your repo`:

```yaml
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i, --style=file]
```
