### ISSUE TITLE
include-what-you-use does not fail

### ISSUE THREAD

**Issue by donion74** [pocc/pre-commit-hooks#55]
include-what-you-use does not fail even if it is supposed to fail. I needed to modify my pre-commit yaml file to include the line `entry`:

```
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: uncrustify
      - id: include-what-you-use
        entry: include-what-you-use -Xiwyu --error=1
```
