### ISSUE TITLE
Configurable `uncrustify` executable path for the 

### ISSUE THREAD

**Issue by skelly37** [pocc/pre-commit-hooks#57]
I have seen in [the hook's code](https://github.com/pocc/pre-commit-hooks/blob/master/hooks/uncrustify.py#L15) that `uncrustify` is hardcoded as a command. It would be really useful to specify some custom path for the executable, e.g. `/home/skelly37/.local/bin/uncrustify`. 

If I can already do something like this, I would appreciate showing me how to do it.

**Comment by skelly37** [comment]
> also want to know how to provide custom path to uncrustify.cfg that is not necessarily at the root level
@bakkiraju It is actually handled by the `uncrustify` itself. You basically pass the path like this

```yaml
hooks:
      - id: uncrustify
        args: [-c, path/to/uncrustify.cfg]
```
