### ISSUE TITLE
clang-tidy: for the -p option: may not occur within a group!

### ISSUE THREAD

**Issue by qawiretu** [pocc/pre-commit-hooks#58]
Hi, I am trying to use the clang-tidy hook.
my .pre-commit-config.yaml looks something like:
`repos:
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
    -   id: clang-tidy
        args: ['-p some/folder']`

Notice the args. I specify the path to the database.

When trying to run, I get:
`clang-tidy: for the -p option: may not occur within a group!
error: clang-tidy: Unknown command line argument '-p build/meson'.  Try: 'clang-tidy --help'
clang-tidy: Did you mean '-p'?`

Thank you for your help

**Comment by brianwatersmanna** [comment]
Use the following:
```
repo: https://github.com/pocc/pre-commit-hooks
rev: master
hooks:
    - id: clang-tidy
      args: [-p=some/folder]
```
