### ISSUE TITLE
clang-format not accepting -i

### ISSUE THREAD

**Issue by guihao-liang** [pocc/pre-commit-hooks#9]
## minimal repro

```
repos:
- repo: https://github.com/pocc/pre-commit-hooks
  sha: master
  hooks:
  - id: clang-format
    args: [--style=Google, -i]
    exclude: \.pb\.(h|cc)$
```

---

## errors

```
clang-format.............................................................Failed
- hook id: clang-format
- exit code: 2

diff: missing operand after `/dev/fd/63'
diff: Try `diff --help' for more information.
diff: missing operand after `/dev/fd/63'
diff: Try `diff --help' for more information.
```

---

## potential root cause

modified utils,

```
function diff_formatted {
   69   # Quoting $1 interferes with array creation
   70   # shellcheck disable=SC2206
   71   args=($1)
   72   filename="$2"
+  73   echo $filename
   74   if [[ " ${args[*]} " == *" -i "* ]]; then
   75     # Here, diff compares what the file is before and after transform
   76     diff "$filename" <(clang-format "${args[@]}"; cat "$filename")
   77   else
   78     # Otherwise clang-format should send output to stdout, and can be compared
   79     diff "$filename" <(clang-format "${args[@]}")
   80   fi
```

output:

```
-i
diff: missing operand after `/dev/fd/63'
diff: Try `diff --help' for more information.
-i
diff: missing operand after `/dev/fd/63'
diff: Try `diff --help' for more information.
```

The filename is `-i`, which makes the pipe fail.

---

## question

clang-format supports `-i`, why you don't want to use it but use `diff` instead?
